"""The dragon's remark about the day's spending — a funny/insulting one-liner,
generated by the LLM when available, with witty canned fallbacks otherwise."""
from __future__ import annotations

import random

from fastapi import APIRouter, Depends
from sqlalchemy import func, select
from sqlalchemy.orm import Session, joinedload

from ..budget_calc import category_lifebars
from ..classify.service import build_provider
from ..db import get_db
from ..models import Transaction

router = APIRouter(prefix="/api/dragon", tags=["dragon"])


def _day_summary(db: Session) -> dict:
    latest = db.scalar(
        select(func.max(Transaction.date)).where(Transaction.is_split.is_(False))
    )
    if latest is None:
        return {"date": None, "spend": 0.0, "count": 0, "biggest": None, "over_budget": []}

    txns = db.scalars(
        select(Transaction).options(joinedload(Transaction.category))
        .where(Transaction.date == latest, Transaction.amount < 0, Transaction.is_split.is_(False))
    ).all()
    spend = round(sum(-t.amount for t in txns), 2)
    biggest = None
    if txns:
        b = max(txns, key=lambda t: -t.amount)
        biggest = {"payee": b.payee, "amount": round(-b.amount, 2),
                   "category": b.category.name if b.category else None}
    over = [b["name"] for b in category_lifebars(db) if b["over_budget"]]
    return {
        "date": latest.isoformat(),
        "spend": spend,
        "count": len(txns),
        "biggest": biggest,
        "over_budget": over,
    }


def _prompt(s: dict) -> str:
    big = s["biggest"]
    big_str = f"{big['payee']} for CHF {big['amount']} ({big['category']})" if big else "nothing"
    over_str = ", ".join(s["over_budget"]) if s["over_budget"] else "none"
    return (
        "You are a sassy, dramatic pet dragon that hoards your owner's money like "
        "treasure and judges every purchase. In ONE short sentence (max 22 words), "
        "make a funny, mildly insulting but affectionate remark about today's "
        "spending. Swiss francs (CHF). No hashtags, no quotes, no emoji.\n\n"
        f"Today's date: {s['date']}\n"
        f"Total spent today: CHF {s['spend']} across {s['count']} purchases\n"
        f"Biggest purchase: {big_str}\n"
        f"Categories over budget this month: {over_str}\n\n"
        "Your remark:"
    )


def _fallback(s: dict) -> str:
    if s["date"] is None:
        return "No transactions yet? My hoard is as empty as your ambition. Feed me data, mortal."
    if s["spend"] == 0:
        return random.choice([
            "Not a single franc spent today? Either you're broke or finally learning. I approve.",
            "Zero spending today. Boring, but my treasure sleeps soundly.",
        ])
    big = s["biggest"]
    if s["over_budget"]:
        return f"{s['over_budget'][0]} is over budget AGAIN. Even a newborn lizard counts better than you."
    if big and big["amount"] >= 100:
        return f"CHF {big['amount']:.0f} at {big['payee']}? My hoard just shed a single, expensive tear."
    if s["spend"] < 20:
        return f"A mighty CHF {s['spend']:.0f} today. Thrilling. Wake me when you do something reckless."
    return random.choice([
        f"CHF {s['spend']:.0f} across {s['count']} purchases. I'm watching. Always watching.",
        f"CHF {s['spend']:.0f} today. Acceptable. My scales remain unruffled, for now.",
    ])


@router.get("/quip")
def quip(db: Session = Depends(get_db)):
    s = _day_summary(db)
    provider = build_provider()
    text = None
    if provider is not None and provider.available():
        text = provider.generate(_prompt(s))
    source = "ai"
    if not text:
        text = _fallback(s)
        source = "fallback"
    # Keep it tidy: strip stray quotes/whitespace, cap length.
    text = text.strip().strip('"').strip()
    if len(text) > 220:
        text = text[:217].rstrip() + "…"
    return {"quip": text, "source": source, "day": s}
